export const blogsList = [
  {
    id: 1,
    slug: "rueckenschmerzen-uebungen",
    image: "/images/blog/rueckenschmerzen-thumb.jpg",
    date: "15. November 2024",
    heading: "Rückenschmerzen? Diese Übungen helfen wirklich",
    para: "Stundenlanges Sitzen macht den Rücken mürbe – aber mit den richtigen Übungen kannst du gegensteuern und langfristig schmerzfrei bleiben.",
  },
  {
    id: 2,
    slug: "ernaehrung-vor-nach-training",
    image: "/images/blog/ernaehrung-thumb.jpg",
    date: "10. November 2024",
    heading: "Was du vor und nach dem Training essen solltest",
    para: "Die richtige Ernährung kann deine Performance pushen und die Regeneration beschleunigen. Wir zeigen dir, welche Nährstoffe dein Körper wann braucht.",
  },
  {
    id: 3,
    slug: "motivation-training-tipps",
    image: "/images/blog/motivation-thumb.jpg",
    date: "5. November 2024",
    heading: "Keine Lust auf Training? 5 Tricks, die wirklich funktionieren",
    para: "Wir alle kennen diese Tage, an denen die Couch verlockender ist. Mit diesen einfachen Strategien überwindest du den inneren Schweinehund.",
  },
  {
    id: 4,
    slug: "hiit-vs-dauerlauf",
    image: "/images/blog/hiit-thumb.jpg",
    date: "28. Oktober 2024",
    heading: "HIIT oder Dauerlauf – was bringt mehr?",
    para: "Kurz und knackig oder lang und gleichmäßig? Beide Trainingsformen haben ihre Stärken. Wir helfen dir zu entscheiden.",
  },
  {
    id: 5,
    slug: "schlaf-muskelaufbau",
    image: "/images/blog/schlaf-thumb.jpg",
    date: "20. Oktober 2024",
    heading: "So wichtig ist Schlaf für deinen Muskelaufbau",
    para: "Schlaf ist genauso wichtig wie Training und Ernährung. Wir zeigen dir, wie du deine Erholung optimierst.",
  },
  {
    id: 6,
    slug: "anfaengerfehler-vermeiden",
    image: "/images/blog/anfaengerfehler-thumb.jpg",
    date: "15. Oktober 2024",
    heading: "Die 10 häufigsten Anfängerfehler – und wie du sie vermeidest",
    para: "Viele Anfänger machen die gleichen Fehler. Wir zeigen dir, wie du von Anfang an richtig trainierst.",
  },
];
